# Generated by Django 4.0.8 on 2022-11-01 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True, verbose_name='Внутренний id')),
                ('sku', models.CharField(max_length=200, verbose_name='Код товара')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('brand', models.CharField(blank=True, max_length=500, null=True, verbose_name='Бренд')),
                ('basic_sale', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Основная скидка')),
                ('basic_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Цена с основной скидкой')),
                ('client_sale', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Скидка клиента')),
                ('client_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Цена с клиентской скидкой')),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Итоговая цена')),
                ('average_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Средняя цена')),
                ('rating', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Рейтинг')),
                ('feedbacks', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Кол-во отзывов')),
                ('count_in_stock', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Кол-во товаров на складе')),
                ('is_active', models.BooleanField(default=True, verbose_name='В наличие')),
                ('date_updated', models.DateField(verbose_name='Дата обновления')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='Username')),
                ('password', models.CharField(max_length=200, verbose_name='Password')),
                ('host', models.CharField(max_length=200, verbose_name='Host')),
                ('port', models.CharField(max_length=200, verbose_name='Port')),
            ],
            options={
                'verbose_name': 'Proxy',
                'verbose_name_plural': 'Proxy',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Значение')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specs_set', to='app.product', verbose_name='Отзывы')),
            ],
            options={
                'verbose_name': 'Характеристики',
                'verbose_name_plural': 'Характеристика',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=300, null=True, verbose_name='Цвет')),
                ('size', models.CharField(blank=True, max_length=300, null=True, verbose_name='Размер')),
                ('username', models.CharField(blank=True, max_length=500, null=True, verbose_name='Пользователь')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст отзыва')),
                ('create_at', models.CharField(blank=True, max_length=200, null=True, verbose_name='Дата создания отзыва')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_set', to='app.product', verbose_name='Отзывы')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
