# Generated by Django 4.0.8 on 2022-11-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_updated',
            field=models.DateTimeField(verbose_name='Дата обновления'),
        ),
    ]
