# Generated by Django 4.0.8 on 2022-11-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_sale_alter_product_basic_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='average_price',
        ),
        migrations.AddField(
            model_name='product',
            name='price_no_sale',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Цена без скидок'),
        ),
    ]
