# Generated by Django 4.0.8 on 2022-11-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_avg_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='URL'),
        ),
    ]
