# Generated by Django 4.0.8 on 2022-11-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Страна производства'),
        ),
    ]
