# Generated by Django 4.0.8 on 2022-11-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='root_id',
            field=models.CharField(default=1, max_length=200, verbose_name='Root ID'),
            preserve_default=False,
        ),
    ]
