# Generated by Django 4.0.8 on 2022-11-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_root_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='external_id',
        ),
        migrations.AddField(
            model_name='product',
            name='percentage',
            field=models.FloatField(default=0, verbose_name='Кол-во процентов'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=200, unique=True, verbose_name='Код товара'),
        ),
    ]
