# Generated by Django 4.0.8 on 2022-11-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_product_price_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_in_stock_old',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='[Начало] Кол-во товаров на складе'),
        ),
    ]
