# Generated by Django 4.0.8 on 2022-12-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_product_external_id_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_from_1c',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Цена из 1С (РРЦ)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Итоговая цена (ССП)'),
        ),
    ]
