# Generated by Django 4.0.8 on 2022-12-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_product_price_from_1c_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_updated',
            field=models.DateField(verbose_name='Дата обновления'),
        ),
    ]
