# Generated by Django 4.0.8 on 2022-12-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_pricehistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productwb',
            name='is_check',
            field=models.BooleanField(default=True, verbose_name='Check'),
        ),
    ]
